### PR TITLE
Feature rewrite endpoint and logic extended

### PR DESCRIPTION
**Pull request by AkiraJager**
This code is not finished, binary sensors need reMake based on new logic

Aditionaly cleanup is needed, will perform it sometime later

### CODE REVIEW

**Comment by jontofront** [comment]
Is it for testing?

**Comment by AkiraJager** [comment]
> Is it for testing?

You can test it out to sees if all of described sensors are apearing corectly. If no issue appear, i would crate and start a PR with binary sensors

**Comment by jontofront** [comment]
image

**Comment by AkiraJager** [comment]
> image

Okay i now see the issue here, problem is that when we are trying to add Entities to HA we get an error becauses of

Coordinator.data has keys like [1,2,3,4,5] becauses they are returned from Api and our Entities have keys like 'heatPump' because i tried to convert them for readabilyti

WIll leave the original intereger key and use translations

@jontofront  Will make the patch in upcoming days

**Pull request merged**
