### PR TITLE
Master 1.0.0 beta

### PR DESCRIPTION
**Pull request by AkiraJager**

### CODE REVIEW

**Comment by AkiraJager** [comment]
CLOSING for now UNTIL 100% sure everything works

**Comment by AkiraJager** [comment]
@jontofront uploaded more changes to branch, might want to test it :)

**Comment by AkiraJager** [comment]
@jontofront Updated code, made number limits update from API, attempted to add mixers

**Comment by jontofront** [comment]
@AkiraJager 
image

**Comment by AkiraJager** [comment]
@jontofront made a seperatev async method for settings limits

**Comment by AkiraJager** [comment]
@jontofront  cahnged the logic of adding mixer

**Pull request closed without merging**
